name: API Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  API_BASE_URL: https://petstore.swagger.io/v2/
  WEB_BASE_URL: https://useinsider.com/
  API_KEY: special-key
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run your tests
      run: pytest tests/api-tests/ --tracing=retain-on-failure --alluredir=allure-results
    - name: Setup Pages
      if: always()
      uses: actions/configure-pages@v5
    - name: Upload artifact
      if: always()
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: 'allure-results'
    - name: Deploy to GitHub Pages
      if: always()
      id: deployment
      uses: actions/deploy-pages@v4
    