name: Performance Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install locust
    - name: Run your tests
      run: |
        mkdir test-results
        locust -f tests/performance-tests/locustfile.py --headless --users 1 -t 10s -H https://www.n11.com --html test-results/report.html

    - name: Upload report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: report
        path: test-results/report.html
    
    - name: Deploy report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v2
      if: always()
      with:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: test-results 