name: Test Automation CI

on:
  push:
    branches:
      - "**"
  #workflow_dispatch:

env:
  API_BASE_URL: https://petstore.swagger.io/v2

jobs:
  test:
    runs-on: ubuntu-latest
    #strategy:
     # matrix:
      #  browser: [chromium, firefox]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install  # Install Playwright browsers
          sudo apt-get install -y allure  # Install Allure on GitHub runner

      - name: Run API tests (Playwright API)
        run: pytest tests/api-tests/ --alluredir=allure-results

      - name: Allure Report with history
        if: always()
        uses: simple-elf/allure-report-action@v1.12

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report