name: Test Automation CI

on:
  push:
    branches:
      - "**"
  #workflow_dispatch:

env:
  API_BASE_URL: https://petstore.swagger.io/v2

jobs:
  test:
    runs-on: ubuntu-latest
    #strategy:
     # matrix:
      #  browser: [chromium, firefox]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Print brew version
        run: brew --version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install  # Install Playwright browsers
          sudo apt-get install -y allure  # Install Allure on GitHub runner

      - name: Run API tests (Playwright API)
        run: pytest tests/api-tests/ --alluredir=reports/allure-results

      - name: Generate Allure Report
        if: always()
        run: |
          allure generate reports/allure-results -o reports/allure-report --clean
          allure open reports/allure-report &

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report